export { drizzle } from 'drizzle-orm/postgres-js';
export { db } from './client';
export * from './schema';
export * from './services/matching';
export * from './services/pricing';
export * from './services/ingestion';
export * from './services/search';
export * from './services/supplier';
export { MercadoLibreAdapter } from './services/supplier/mercadolibre';
export { AliExpressAdapter } from './services/supplier/aliexpress';
export { AmazonAdapter } from './services/supplier/amazon';
export { EbayAdapter } from './services/supplier/ebay';
export { WalmartAdapter } from './services/supplier/walmart';
export { SheinAdapter } from './services/supplier/shein';
export { TemuAdapter } from './services/supplier/temu';
export { TikTokShopAdapter } from './services/supplier/tiktokshop';
